development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nix
  pool: 5
  username: root
  password: admin
  #socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nix
  pool: 5
  username: root
  password: admin
  #socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nix
  pool: 5
  username: root
  password: admin
  #socket: /var/run/mysqld/mysqld.sock
